### ISSUE TITLE
[Tech]: TON Bridge

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1145]
### Problem statement

We want to transfer tokens between SORA and TON

## Phase 1

- [ ] Outbound channel contract
- [ ] TONApp contract (for TON-only transfers)
- [ ] Relayer from TON to SORA
- [ ] JettonApp pallet (initially only for TON)

## Phase 2

- [ ] Inbound channel contract
- [ ] JettonApp contract
- [ ] Relayer from SORA to TON
- [ ] JettonApp pallet (for both TON and Jettons)

## Phase 3

- [ ] NFTApp contract (need additional research)
- [ ] NFTApp pallet

### Requirements

- Contracts language: TACT with careful review of resulting FunC code
