### ISSUE TITLE
[Tech]: JettonApp pallet (TON only)

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1149]
### Problem statement

We need to handle messages came from TON network

## Phase 1
- [ ] Mint receiver
- [ ] Register app root call

## Phase 2
- [ ] Burn call
- [ ] Refund call (at least manual)
- [ ] Register sidechain asset call
- [ ] Register thischain asset call
- [ ] Fees management
