### ISSUE TITLE
OrderBooks CRUD

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora2-network#336]
# Description
This task lists all the CRUD operations and the corresponding requirements associated to order books

# Sub-tasks

- [x] #311 
- [x] #400
- [x] https://github.com/sora-xor/sora2-network/issues/459
- [x] https://github.com/sora-xor/sora2-network/issues/460
- [x] https://github.com/sora-xor/sora2-network/issues/461
