### ISSUE TITLE
[Tech]: Prepare for 1.10 release

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#405]
### Problem statement

We need to ensure what we are ready for release 1.10

### Definition of Done

- [x] Check and fix runtime configuration and ensure it's correct #403
- [x] Check and fix substrate storage migrations #262 
- [x] Check and fix SORA storage migrations 
- [x] Hide modules which is unneeded to be in production build with feature flags #398
- [x] Check migrations with try-runtime or/and forked-off production network 
- [x] Check compatibility of new runtime with old node binary
- [x] Update pallets weights
- [x] Update versions #415 
- [x] No referendum ongoing during runtime upgrade dispatch

### Requirements

- Make sure everything is working before moving forward with release
