### ISSUE TITLE
[Tech]: Fix Substrate bridge issues

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#765]
### Problem statement

During release of 3.0.0 we found several issues with the Substrate bridge

### Definition of Done

- [x] Use on-chain storage for commitments #757 
- [x] Use ThisNetworkId constant in multisig-verifier instead of storage value #757 
- [x] Don't print relayer parameters to log, because it may contain sensetive data #759 
- [x] Make it imposibble to call inboundChannel.submit with Empty proof externally even if it's compiled with runtime-benchmarks #757 
- [x] Load commitments only from Finalized blocks #757
